# Generated by Django 4.2.6 on 2023-10-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки отправки')),
                ('status_try', models.CharField(max_length=50, verbose_name='Статус попытки')),
                ('answer', models.CharField(max_length=250, null=True, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.CreateModel(
            name='Mailling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Дата и время начала рассылки')),
                ('date_end', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
                ('periodicity', models.CharField(choices=[('DAILY', 'раз в день'), ('WEEKLY', 'раз в неделю'), ('MONTHLY', 'раз в месяц')], max_length=50, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'создана'), ('started', 'запущена'), ('closed', 'завершена')], default='created', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_letter', models.CharField(max_length=100, verbose_name='Тема рассылки')),
                ('body_letter', models.TextField(verbose_name='Тело рассылки')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
