# Generated by Django 4.2.6 on 2023-10-15 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailling', '0001_initial'),
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='mailling',
            name='client',
            field=models.ManyToManyField(to='client.client', verbose_name='Кому'),
        ),
        migrations.AddField(
            model_name='mailling',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailling.message', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='mailling',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='logs',
            name='mailling_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailling.mailling', verbose_name='Рассылка'),
        ),
    ]
